url: http://rrsoft.co
baseurl: ''

# Site settings
title: Rapid River Software
email: info@rrsoft.co
description: "Rapid River Software is a worldwide group of full-stack developers with skills ranging from front-end to operations automation, and everything in between. We have more than four decades of experience writing software for the Internet. Whether designing new systems, or improving existing ones, we have the skills to hit the ground running."

# Team names, titles and social links
people:
- name: Nick Marden
  pic: 1
  position: Founder & CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nick-marden-591326
    - title: github
      url: https://github.com/nickmarden
    - title: twitter
      url: https://twitter.com/nickmarden
    - title: facebook
      url: https://www.facebook.com/nickmarden

- name: Calum Halcrow
  pic: 2
  position: Founder & CTO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Yury Stepanov
  pic: 3
  position: Software Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Martha Thompson
  pic: martha
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/MothOnMars
    - title: linkedin
      url: https://www.linkedin.com/in/marthathompson007

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile*
  - LICENSE
