inc:
  # Blog Information
  title:        "Rapid River Software"
  subtitle:     "Hi, we're Rapid River, we get things done."
  cover_image:  header.jpg
  logo:         logo.jpg

  # Company information
  company:      Rapid River Software
  url:          http://rrsoft.co/
  facebook:     rapidriversoftware
  twitter:      sendtoinc
  about_link:   /about/

  # Product Information
  product_link: http://rrsoft.co/
  tagline:      "Hi, we're Rapid River, we get things done."

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      false
    hn:         false

 # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://rrsoft.co
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
