url: http://rrsoft.co
baseurl: ''

# Site settings
title: Rapid River Software
email: info@rrsoft.co
description: "Rapid River Software is a worldwide group of full-stack developers with skills ranging from front-end to operations automation, and everything in between. We have more than four decades of experience writing software for the Internet. Whether designing new systems, or improving existing ones, we have the skills to hit the ground running."

# Team names, titles and social links
people:
- name: Calum Halcrow
  pic: calum
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/calumhalcrow
    - title: github
      url: https://github.com/calumhalcrow
    - title: twitter
      url: https://twitter.com/calumhalcrow
    - title: facebook
      url: https://www.facebook.com/calumhalcrow

- name: Yury Stepanov
  pic: yury
  position: Software Engineer
  social:
    - title: facebook
      url: https://www.facebook.com/yurgen.kulikow

- name: Lim Victor
  pic: victor
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/viclim
    - title: linkedin
      url: https://www.linkedin.com/in/victorlim

- name: Ivan Yeoh
  pic: ivan
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/ivanyeoh
    - title: facebook
      url: https://www.facebook.com/yeohweiboon
    - title: twitter
      url: https://twitter.com/ivanyeoh
    - title: linkedin
      url: https://www.linkedin.com/in/ivan-yeoh-14391855

- name: Aaron Lim
  pic: aaron
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/aaron-lim

- name: Jimmy Ngu
  pic: jimmy
  position: Engineering Team Lead
  social:
    - title: github
      url: https://github.com/jimmynguyc
    - title: facebook
      url: https://www.facebook.com/jimmyngu
    - title: twitter
      url: https://twitter.com/jimmynguyc
    - title: linkedin
      url: https://www.linkedin.com/in/jimmyngu

- name: Anton Lvov
  pic: anton
  position: Senior Software Developer
  social:
    - title: github
      url: https://github.com/denied404
    - title: facebook
      url: https://www.facebook.com/anton.lvov.90
    - title: twitter
      url: https://twitter.com/404_denied
    - title: linkedin
      url: https://www.linkedin.com/in/anton-lvov-6109aa36

- name: Karuna Krishnasamy
  pic: karuna
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/snowflakekiller
    - title: facebook
      url: https://www.facebook.com/sn0wflakekiller
    - title: twitter
      url: https://twitter.com/snowflakekiller
    - title: linkedin
      url: https://www.linkedin.com/in/karunaskj

- name: Kavitha Nadarajah
  pic: kavitha
  position: HR & Admin Manager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kavitha-nadarajah-6776992b
    - title: facebook
      url: https://www.facebook.com/nkavitha
    - title: instagram
      url: https://www.instagram.com/nkavitha

- name: Tamer Shlash
  pic: tamer
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/TamerShlash
    - title: stack-overflow
      url: https://stackoverflow.com/users/368167
    - title: linkedin
      url: https://www.linkedin.com/in/tamershlash

- name: Lim Yih En
  pic: yihen
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/yih-en
    - title: linkedin
      url: https://www.linkedin.com/in/yih-en-lim-16882b99/

- name: Adeline Lim
  pic: adeline
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/adelinelim
    - title: linkedin
      url: https://www.linkedin.com/in/adeline-lim-593953141/

- name: Waihon Yew
  pic: waihon
  position: Engineering Team Lead
  social:
    - title: github
      url: https://github.com/waihon
    - title: twitter
      url: https://twitter.com/waihon
    - title: linkedin
      url: https://www.linkedin.com/in/waihonyew

- name: Hakim Ahmad
  pic: hakim
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/Congrammers
    - title: facebook
      url: https://www.facebook.com/hakim.ahmad.1466
    - title: linkedin
      url: https://www.linkedin.com/in/hakimthedev

- name: Iqbal Hasnan
  pic: iqbal
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/iqbalhasnan
    - title: linkedin
      url: https://www.linkedin.com/in/iqbalhasnan

- name: Fahmi San
  pic: fahmi
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/fahmisan88
    - title: linkedin
      url: https://www.linkedin.com/in/ahmad-fahmi-san-ahmad-8763b7131/

- name: Shaii Ong
  pic: shaii
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/monsteronfire
    - title: twitter
      url: https://twitter.com/monsteronfire
    - title: linkedin
      url: https://www.linkedin.com/in/shaii-ong

- name: Halah Abuateeq
  pic: halah
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/HalahAb
    - title: linkedin
      url: https://www.linkedin.com/in/halah-abuateeq/
- name: 'Fatima "Sarah" Maisarah Moktar'
  pic: sarah
  position: HR & Admin Executive
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/fatima-maisarah-moktar-a4505b131/

- name: Carlos Lima
  pic: carlos
  position: Engineering Team Lead
  social:
    - title: github
      url: https://github.com/carloslima
    - title: linkedin
      url: https://www.linkedin.com/in/carloslimabr/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RapidRiverSoftware
  - title: facebook
    url: https://facebook.com/rapidriversoftware
  - title: instagram
    url: https://instagram.com/rapidriversoftware

# Postal address (add as many lines as necessary)
address:
  - line: The Vertical Business Suites
  - line: Avenue 3 Bangsar South City
  - line: No. 8 Jalan Kerinchi, 59200 Kuala Lumpur

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile*
  - LICENSE
  - vendor
