url: https://rrsoft.co
baseurl: ''
# Site settings
title: Rapid River Software
email: info@rrsoft.co
description: "Rapid River Software is a worldwide group of full-stack developers. We have skills ranging from front-end to operations automation and everything in between. With extensive experience writing software for the Internet, whether it's designing new systems or improving existing ones, we have the skills to hit the ground running."
map: "https://goo.gl/maps/1TAqia2N7gYPWcCz5"
telephone: "+60322423731"

collections:
  careers:
    output: true
  case_studies:
    output: true
  solutions:
    output: true
  capabilities:
    output: true

sass:
  sass_dir: _scss

# Syntax highlighting
markdown: kramdown
highlighter: rouge

# pagination settings
plugins:
  - jekyll-paginate
  
paginate: 8
paginate_path: "/blog/page/:num/"

# Company social media links
social:
  - title: github
    url: https://github.com/RapidRiverSoftware
  - title: facebook
    url: https://facebook.com/rapidriversoftware
  - title: instagram
    url: https://instagram.com/rapidriversoftware

# Postal address (add as many lines as necessary)
address:
  - line: The Vertical Business Suites
  - line: Avenue 3 Bangsar South City
  - line: No. 8 Jalan Kerinchi, 59200 Kuala Lumpur

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile*
  - LICENSE
  - vendor

include:
  - _redirects
