require('jquery');
require('bootstrap');
require('./jquery.easing.min');
require('./classie');
require('./jqBootstrapValidation');
require('./cbpAnimatedHeader.min');
require('./modernizr');
require('./agency');
require('./test1');
